### ISSUE TITLE
Issue with special characters

### ISSUE THREAD

**Issue by MiLk** [Xephi/AuthMeReloaded#206]
I have installed AuthMeReloaded on my Spigot server, but I have an issue with the french translation.

When the server start, it replaces the content of the `plugins/AuthMe/messages_fr.yml` file and replace all the special characters by hexadecimal code.

Instead of https://github.com/Xephi/AuthMeReloaded/blob/master/src/main/resources/messages_fr.yml, I get the following:
```yaml
# Traduction par: André
unknown_user: "&fUtilisateur non enregistr\xc3\xa9"
unsafe_spawn: "&fT\xc3\xa9l\xc3\xa9portation dans un endroit s\xc3\xbbr"
not_logged_in: "&cNon connect\xc3\xa9!"
reg_voluntarily: '&fVous venez d''arriver? faites un "/register motdepasse confirmermotdepasse"'
usage_log: '&cUtilisez: /login motdepasse'
wrong_pwd: '&cMauvais MotdePasse'
unregistered: "&cCe compte a \xc3\xa9t\xc3\xa9 supprim\xc3\xa9!"
reg_disabled: "&cL'enregistrement est d\xc3\xa9sactiv\xc3\xa9"
valid_session: "&cVous \xc3\xaates authentifi\xc3\xa9"
login: "&cConnection effectu\xc3\xa9e!"
vb_nonActiv: '&fCe compte n''est pas actif, consultez vos emails!'
user_regged: "&cCe nom est deja utilis\xc3\xa9.."
usage_reg: '&cUtilisez la commande /register motdepasse confirmermotdepasse'
...
```

What do I do wrong?

The server is running with the following parameter: `-DFiles.encoding=UTF8`.

Server version: `This server is running CraftBukkit version git-Spigot-fdc1440-53fac9f (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)`
AuthMe version: `5.0-beta3`
Java version: 
```
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```

**Comment by sgdc3** [comment]
are you saving the file with UTF8 non-BOM encoding?

**Comment by MiLk** [comment]
Yes. Even downloaded directly from github with `wget` doesn't change anything.
I can correctly display the file with `vim`, `cat` or `less` before starting the server.

**Comment by FoxColdMetal** [comment]
I found this problem in the early ```v3.5-SNAPSHOT```. To prevent Authme to rewrite the messages file on every start, you can set the read-only flag on your ```messages_fr.yml``` file, at filesystem level.

This is not a final solution, but does the trick to preserve your custom changes on the file while the issue is being solved. Note that if the yaml file contains syntax errors, Authme won't be able to fix and save them to the file again while the flag is set.

**Comment by DNx5** [comment]
@sgdc3 can you build that ^

**Comment by sgdc3** [comment]
build is automated
http://ci.xephi.fr/job/DEVBUILD-ONLY/

**Comment by FoxColdMetal** [comment]
The language file is not rewritten anymore. It is solved.

**Comment by sgdc3** [comment]
Is the issue fixed? :)

**Comment by FoxColdMetal** [comment]
I have tested the new plugin snapshot with the same configuration as @MiLk used:
* Server version ```1.8.8-R0.1-SNAPSHOT``` with parameter ```-DFiles.encoding=UTF8```.
* Authme configured to use french language and the referenced ```messages_fr.yml``` language file (https://github.com/Xephi/AuthMeReloaded/blob/master/src/main/resources/messages_fr.yml).

As result, the language file is no longer rewritten and remains intact after each start, with no escaped characters as before.

**Comment by MiLk** [comment]
Thanks for your help.
The file is no longer rewritten, but I still have an issue.
![2015-09-15-102442_420x42_scrot](https://cloud.githubusercontent.com/assets/29782/9865644/20d8c2a4-5b94-11e5-9766-b23d097bcd00.png)

**Comment by DNx5** [comment]
is minecraft support displaying special characters?

**Comment by MiLk** [comment]
It works with Essentials.

**Comment by FoxColdMetal** [comment]
Minecraft client supports UTF8 encoding long time ago, by default. So these special characters must be supported.

I have been doing some testing. Running the server on a Linux host (tested in ubuntu 14.04) and encoding the file with UTF8 without BOM, the special characters are shown properly on the client. Running the server on a Windows host and encoding the file with ANSI (CP-1252), the special characters are shown properly too.

So i think the problem may be the way the Yaml engine opens and process the file streams and the character encoding it uses to decode them. In the best of cases should be a simple misconfiguration.

**Comment by FoxColdMetal** [comment]
Nope :)

Although I already had a working fix by modifying some code of the Yaml engine derived classes (overloading some methods in ```fr.xephi.authme.settings.CustomConfiguration``` class), this was unnecessary.

@MiLk try changing the JVM parameter ```-DFiles.encoding=UTF8``` by this one ```-Dfile.encoding=UTF-8```.

**Comment by MiLk** [comment]
Works! Thank you for your help.

**Comment by Xephi** [comment]
@MiLk  un petit soucis avec la langue Française? :') N'hésite pas à convertir le fichier messages_fr.yml en UTF-8 pour ne pas avoir de soucis, mais cela dépend de l'os qui fait tourner le serveur, si tu es sous Linux, UTF-8 semble une bonne idée, par contre si tu es sous Windows, n'hésite pas à le convertir en ANSI (CP-1252 si je ne m'abuse)

Xephi
