### ISSUE TITLE
Server crash on starting

### ISSUE THREAD

**Issue by NIK220V** [Xephi/AuthMeReloaded#221]
Starting from #231 dev build (#230 and prev works fine)
[09-24 20:32:35] java.lang.NullPointerException
	at fr.xephi.authme.settings.Settings.<init>(Settings.java:99)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:120)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:418)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:382)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:337)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:256)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528)
	at java.lang.Thread.run(Thread.java:745)

**Comment by DNx5** [comment]
fixed, try build 232

**Comment by sgdc3** [comment]
@NIK220V Can you try latest dev build at http://ci.xephi.fr/job/DEVBUILD-ONLY/ ? Thanks

**Comment by NIK220V** [comment]
@sgdc3 What should i check? Email recovery system?

**Comment by sgdc3** [comment]
@NIK220V No the error on start you reported here :)

**Comment by NIK220V** [comment]
@sgdc3 Okay, one second, i'll update. Can you say when you'll be able to add more messages fro email system? Because i still don't know did i something wrong or this is a plugin error.

**Comment by NIK220V** [comment]
@sgdc3 Oh. Wow. It doesn't even run. Like there is no plugin in /pl such as 'AuthMe'. I think you broke something :D

**Comment by NIK220V** [comment]
@sgdc3 Here it is.
[01:22:09] [Server thread/ERROR]: Could not load 'plugins/AuthMe-5.1-SNAPSHOT (1).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketListener
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot187.jar:git-Spigot-f928e7a-f27339c]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot187.jar:git-Spigot-f928e7a-f27339c]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot187.jar:git-Spigot-f928e7a-f27339c]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:291) [spigot187.jar:git-Spigot-f928e7a-f27339c]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot187.jar:git-Spigot-f928e7a-f27339c]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [spigot187.jar:git-Spigot-f928e7a-f27339c]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketListener
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_45]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot187.jar:git-Spigot-f928e7a-f27339c]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot187.jar:git-Spigot-f928e7a-f27339c]
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.events.PacketListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot187.jar:git-Spigot-f928e7a-f27339c]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot187.jar:git-Spigot-f928e7a-f27339c]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_45]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_45]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_45]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot187.jar:git-Spigot-f928e7a-f27339c]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot187.jar:git-Spigot-f928e7a-f27339c]
	... 6 more

**Comment by sgdc3** [comment]
protocollib is a necessary dependency atm, we'll add it as softdepend very soon

**Comment by sgdc3** [comment]
so try to put protocollib in you plugin folder

**Comment by NIK220V** [comment]
Yeah. Works fine with ProtocolLib.

**Comment by sgdc3** [comment]
Ok can you close the issue? ;)
