### ISSUE TITLE
Email Recovery's content can't display Chinese charactors

### ISSUE THREAD

**Issue by smartmadio** [Xephi/AuthMeReloaded#269]
Hello,I enabled email recovery and wrote 'mailText' in Chinese Today.When I tested it ,I found all Chinese charactors in the the password recovery mail content displayed as ??? but the mail title can display Chinese charactors correctly.

(I've tried to transform coding format of config.yml into UTF-8 or GBK but it still don't work.)

Current Minecraft-Spigot version: 1.8.8
Current authme version: AuthMeReloaded-Dev #339

**Comment by Xephi** [comment]
Can you please try to add '-Dfile.encoding=UTF-8' into server line command starting and tell me if that work ?

**Comment by smartmadio** [comment]
@Xephi I've added '-Dfile.encoding=UTF-8'  into server line command starting,but it didn't work too.

**Comment by DNx5** [comment]
we should move it into a file.

**Comment by sgdc3** [comment]
What do you mean @DNx5 ?

**Comment by DNx5** [comment]
mailText value

**Comment by Xephi** [comment]
Can you please try latest dev build and tell me if the email.html works ?

Xephi

**Comment by smartmadio** [comment]
Testing on it :-)

**Comment by smartmadio** [comment]
[Craft Scheduler Thread - 3/WARN]: org.apache.commons.mail.EmailException: Invalid message supplied
	at org.apache.commons.mail.HtmlEmail.setHtmlMsg(HtmlEmail.java:151)
	at fr.xephi.authme.SendMailSSL$1.run(SendMailSSL.java:84)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Authme version:#472

**Comment by smartmadio** [comment]
I‘ve put email.html in authme folder,and it can start up now.But,still,there's ??????????????? instead of Chinese charactors in the email I received.(Tested on adding '-Dfile.encoding=UTF-8' or not adding '-Dfile.encoding=UTF-8' and changing email.htm to 'UTF-8 no bom' or GBK .

**Comment by smartmadio** [comment]
Besides,<image>,<playername>,<generatedpass>,<servername> in the email.html won't work.

**Comment by sgdc3** [comment]
@Xephi

**Comment by Xephi** [comment]
Fixed

**Comment by smartmadio** [comment]
Got it,I'll test on it.

**Comment by smartmadio** [comment]
`[09:20:26 WARN]: org.apache.commons.mail.EmailException: Invalid message supplied
        at org.apache.commons.mail.HtmlEmail.setHtmlMsg(HtmlEmail.java:151)
        at fr.xephi.authme.SendMailSSL$1.run(SendMailSSL.java:84)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
`

**Comment by smartmadio** [comment]
Still can't find email.html.
I'll write email.html using dreamwaver and put it in authme folder and have another test.

**Comment by smartmadio** [comment]
This's what I've wrote in email.html:
```
<html>
<div style="background-color:blue;">
Chinese charactors：中文测试<br />
Player Name：<playername><br />
Server Name：<servername><br />
Password：<generatedpass><br />
<image><br />
</div>
</html>
```
This's the content of the email I've received:
```
Chinese charactors?????
Player Name?
Server Name?
Password?
```

**Comment by smartmadio** [comment]
I've read https://github.com/Xephi/AuthMeReloaded/commit/e781115d7cf66db57a436de8d21693aa05d50be3 seems something wrong in email.html,then,another test:
1.email.html:
```
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
</head>
<body>
<div style="background-color:blue;">
Chinese charactors:中文测试<br />
Player Name:%playername%<br />
Server Name:%servername%<br />
Password:%generatedpass%<br />
<image><br />
</div>
</body>
</html>
```
This's content of the mail I've received:
```
Chinese charactors:????
Player Name:123777
Server Name:YiHaiFengLan Minecraft Server
Password:kofflt1b
```

**Comment by smartmadio** [comment]
Testing AuthMeReloaded-Dev #5​83:
email.html:
```
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
</head>
<body>
<div style="background-color:blue;">
Chinese charactors:中文测试<br />
Player Name:<playername><br />
Server Name:<servername><br />
Password:<generatedpass><br />
%image%<image><br />
</div>
</body>
</html>
```
This's content of the mail I've received:
```
Chinese charactors:????
Player Name:
Server Name:
Password:
%image%
```
`<image>` or `%image%` won't work,all Chinese charactors in the mail content still displayed as ???.

**Comment by smartmadio** [comment]
Testing AuthMeReloaded-Dev #5​83,This version could creat email.html now.
email.html:
```
<html lang="zh-CN">
<head>
<meta charset="GBK">
</head>
<body>
<div style="background-color:blue;">
Chinese charactors:中文测试\u4e2d\u6587\u6d4b\u8bd5<br />
Player Name:<playername><br />
Server Name:<servername><br />
Password:<generatedpass><br />
%image%<image><br />
</div>
</body>
</html>
```
This's content of the mail I've received:
```
Chinese charactors:????\u4e2d\u6587\u6d4b\u8bd5
Player Name:
Server Name:
Password:
%image%
```
`<image>` or `%image%` won't work,all Chinese charactors in the mail content still displayed as ???.

**Comment by Xephi** [comment]
Here is a good usage of the email.html :
https://github.com/AuthMe-Team/AuthMeReloaded/blob/master/src/main/resources/email.html

By the way, i will check why Chinese charactors are not displayed correctly, try to encode email.html as utf-8 :/

**Comment by Xephi** [comment]
@smartmadio Can you please try with this build :
http://ci.xephi.fr/job/AuthMeReloaded-Dev/584/

**Comment by smartmadio** [comment]
OK,I'll have a try

**Comment by smartmadio** [comment]
@Xephi Test finished.The mail content could display Chinese charactors correctly now:)
